[project]
name = "my-profile"
version = "0.1.1"
description = "Application for displaying my profile"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-generativeai>=0.8.5",
]
